### ISSUE TITLE
Auto-generate link lists for the startpage of www.sommerfeld.io

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/website#17]
As a developer and owner of [www.sommerfeld.io](http://www.sommerfeld.io/), I want to auto-generate content for my website's start page. The auto-generated content should include two link lists:
- one listing my personal projects from GitHub, with links to their respective documentation pages,
- and another listing projects from the "sommerfeld-io" GitHub organization, also linking to their respective documentation pages.

By auto-generating these link lists, I aim to keep the start page of [www.sommerfeld.io](http://www.sommerfeld.io/) up-to-date with the latest projects and their corresponding documentation. This will save me time and effort in manually updating the links whenever there are new projects or changes in the GitHub repositories.

Additionally, the auto-generation feature will ensure that visitors to my website can easily navigate to the documentation pages for my personal projects and the projects under the "sommerfeld-io" organization on GitHub, enhancing the overall user experience and promoting better engagement with the content on my website.

### Acceptance Criteria
- [x] Each list should come as a separate asciidoc partials file
- [x] Each list should contain a intro-line (most likely the one from the github repo or maybe the first line of the readme).
- [x] Implement personal projects
- [x] Implement organization projects
- [x] Both partials files should be included in docs/modules/ROOT/pages/index.adoc
- [x] Should be part of the `docs-as-code.yml` pipeline of this repo
- [x] Update all `antora.yml` files (change module name to match the repo name)
- [x] Check jarvis if the `antora.yml` is written correctly (module name = repo name)
- [x] exclude repos
    - personal
        - trashbox
        - provinzial
        - job
        - configs-persistent-data
        - archive
    - org
        - .github
- [x] Remove Personal projects dropdown from theme and links from nav.adoc

### Implementation ideas / thoughts
Query Github api (or use github CLI) or read from antora playbooks? Querying github prpbably would allow reading the repo description as well.

Implement as a new step which runs in parallel to the current steps. Consider checking out the code base with a dedicated branch name to avoid conflicts.

```yaml
        # CONSIDER THIS when checking out the latest code base:
        # https://github.com/actions/checkout/issues/439#issuecomment-830862188
        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, uses the default branch.
        # To get the latest code base, the branch must be specified explicitely
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
``` 

But maybe just adding a step to the existing jobs without anything in parallel is just easier and avoids potential conficts.
